
package com.example.wso2adminservice.generate.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RemoteUserStoreManagerServiceUserStoreException", targetNamespace = "http://service.ws.um.carbon.wso2.org")
public class RemoteUserStoreManagerServiceUserStoreException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RemoteUserStoreManagerServiceUserStoreException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message, RemoteUserStoreManagerServiceUserStoreException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RemoteUserStoreManagerServiceUserStoreException_Exception(String message, RemoteUserStoreManagerServiceUserStoreException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.wso2adminservice.generate.ws.RemoteUserStoreManagerServiceUserStoreException
     */
    public RemoteUserStoreManagerServiceUserStoreException getFaultInfo() {
        return faultInfo;
    }

}
